# Generated by Django 5.1.6 on 2025-06-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=10, null=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Mode', models.CharField(max_length=10, null=True)),
                ('Category', models.CharField(max_length=20, null=True)),
                ('Type', models.CharField(max_length=10, null=True)),
                ('Skill', models.CharField(max_length=100, null=True)),
                ('Duration', models.TimeField(null=True)),
                ('Count', models.CharField(max_length=3, null=True)),
                ('Group_count', models.IntegerField(max_length=2, null=True)),
            ],
        ),
    ]
