# Generated by Django 5.1.6 on 2025-06-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='Section',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='Group_count',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
