# Generated by Django 5.1.6 on 2025-06-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_program_section_alter_program_group_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='Duration',
            field=models.IntegerField(null=True),
        ),
    ]
