# Generated by Django 5.1.6 on 2025-06-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_alter_program_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='Duration',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
