# Generated by Django 5.1.6 on 2025-07-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_alter_program_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='programDuration',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
