# Generated by Django 5.1.6 on 2025-07-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_program_programduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_quiz',
            field=models.BooleanField(null=True),
        ),
    ]
