# Generated by Django 5.1.6 on 2025-07-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_program_is_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='nav_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
