# Generated by Django 5.1.6 on 2025-07-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0007_nav_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nav_items',
        ),
    ]
