# Generated by Django 5.1.6 on 2025-07-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0009_onlineprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adno', models.CharField(max_length=5, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('father', models.CharField(max_length=50, null=True)),
                ('locality', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('village', models.CharField(max_length=50, null=True)),
                ('grade', models.CharField(max_length=3, null=True)),
                ('house', models.CharField(max_length=50, null=True)),
                ('point', models.IntegerField(max_length=10, null=True)),
            ],
        ),
    ]
