# Generated by Django 5.1.6 on 2025-07-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0011_student_assigned_by_alter_student_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='scode',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
