# Generated by Django 5.1.6 on 2025-08-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0014_remove_program_category_remove_program_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlineprofile',
            old_name='last_login',
            new_name='last_seen',
        ),
    ]
