# Generated by Django 5.1.6 on 2025-08-23 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0015_rename_last_login_onlineprofile_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='duration',
        ),
        migrations.AddField(
            model_name='program',
            name='event_duration',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='mlm_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='urd_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='count',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_duration',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='programparticipant',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_programs', to='controller.student'),
        ),
        migrations.AlterField(
            model_name='programparticipant',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_participants', to='controller.program'),
        ),
    ]
