# Generated by Django 5.1.6 on 2025-08-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0016_remove_program_duration_program_event_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='group_count',
            field=models.IntegerField(null=True),
        ),
    ]
