# Generated by Django 5.1.6 on 2025-08-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0018_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='category',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='house',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='mode',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='section',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='skill',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='type',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
