# Generated by Django 5.1.6 on 2025-08-24 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0019_adminsetting_category_adminsetting_house_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminsetting',
            old_name='category',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='adminsetting',
            old_name='house',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='adminsetting',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='adminsetting',
            name='section',
        ),
        migrations.RemoveField(
            model_name='adminsetting',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='adminsetting',
            name='type',
        ),
    ]
