# Generated by Django 6.0.4 on 2026-06-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0020_rename_category_adminsetting_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='category',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='judging_conditions',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='section',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='skill',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='type',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='selected_grade',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
