# Generated by Django 6.0.4 on 2026-07-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0021_adminsetting_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
