# Generated by Django 6.0.4 on 2026-07-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0022_student_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='bidding_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
