# Generated by Django 6.0.4 on 2026-07-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0023_adminsetting_bidding_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsetting',
            name='bidding_enabled',
        ),
    ]
