# Generated by Django 6.0.4 on 2026-07-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0024_remove_adminsetting_bidding_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='bidding_mode',
            field=models.BooleanField(default=False),
        ),
    ]
