# Generated by Django 6.0.4 on 2026-07-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0025_adminsetting_bidding_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='min_bid_amount',
            field=models.IntegerField(default=1000),
        ),
    ]
