# Generated by Django 6.0.4 on 2026-07-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0026_adminsetting_min_bid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
