# Generated by Django 6.0.4 on 2026-07-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0027_student_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='active_bid_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='active_bid_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='active_bid_leader_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='active_bid_student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
