# Generated by Django 6.0.4 on 2026-07-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0028_adminsetting_active_bid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='auction_active',
            field=models.BooleanField(default=False),
        ),
    ]
