# Generated by Django 6.0.4 on 2026-07-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0029_adminsetting_auction_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='current_turn_step',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='selection_round_active',
            field=models.BooleanField(default=False),
        ),
    ]
