# Generated by Django 6.0.4 on 2026-07-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0030_adminsetting_current_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='leader_order',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
