# Generated by Django 6.0.4 on 2026-07-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0031_adminsetting_leader_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='candidate_registration_active',
            field=models.BooleanField(default=False),
        ),
    ]
