# Generated by Django 6.0.4 on 2026-07-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0032_adminsetting_candidate_registration_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='bid_confirmation_duration',
            field=models.IntegerField(default=10),
        ),
    ]
