# Generated by Django 6.0.4 on 2026-07-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0033_adminsetting_bid_confirmation_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='avg_biddable_count',
            field=models.IntegerField(default=3),
        ),
    ]
