# Generated by Django 6.0.4 on 2026-07-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0034_adminsetting_avg_biddable_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
