# Generated by Django 6.0.4 on 2026-07-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0035_alter_program_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('program_type', models.CharField(blank=True, max_length=10, null=True)),
                ('program_mode', models.CharField(blank=True, max_length=10, null=True)),
                ('min_count', models.IntegerField(default=0)),
                ('max_count', models.IntegerField()),
            ],
        ),
    ]
