# Generated by Django 6.0.4 on 2026-07-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0036_participationrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationrule',
            name='is_multilingual',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participationrule',
            name='language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participationrule',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participationrule',
            name='skill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='is_multilingual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='max_entries_per_house',
            field=models.IntegerField(blank=True, help_text='Max participants/teams a single house can send to this program', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='max_participants',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='program',
            name='min_participants',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='program',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programparticipant',
            name='role',
            field=models.CharField(default='Participant', max_length=20),
        ),
    ]
