# Generated by Django 6.0.4 on 2026-07-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0037_participationrule_is_multilingual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='max_participants',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='min_participants',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
