# Generated by Django 6.0.4 on 2026-07-19 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0038_alter_program_max_participants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='controller.student')),
            ],
        ),
        migrations.CreateModel(
            name='FestConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidding_mode', models.BooleanField(default=False)),
                ('auction_active', models.BooleanField(default=False)),
                ('min_bid_amount', models.IntegerField(default=1000)),
                ('bid_confirmation_duration', models.IntegerField(default=10)),
                ('avg_biddable_count', models.IntegerField(default=3)),
                ('selection_round_active', models.BooleanField(default=False)),
                ('current_round', models.IntegerField(default=1)),
                ('current_turn_step', models.IntegerField(default=0)),
                ('leader_order', models.CharField(blank=True, max_length=500, null=True)),
                ('candidate_registration_active', models.BooleanField(default=False)),
                ('selected_grade', models.CharField(blank=True, max_length=100, null=True)),
                ('judging_conditions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveAuctionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_highest_amount', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('current_highest_bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction_state', to='controller.student')),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_type', models.CharField(choices=[('CATEGORY', 'Category'), ('SKILL', 'Skill'), ('TYPE', 'Program Type'), ('MODE', 'Program Mode'), ('OTHER', 'Other')], max_length=50)),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminSetting',
        ),
    ]
