# Generated by Django 6.0.4 on 2026-07-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0039_bidlog_festconfiguration_liveauctionstate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='setting_type',
            field=models.CharField(choices=[('CATEGORY', 'Category'), ('SKILL', 'Skill'), ('TYPE', 'Program Type'), ('MODE', 'Program Mode'), ('HOUSE', 'House'), ('FEST_NAME', 'Fest Name'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
