# Generated by Django 6.0.4 on 2026-07-19 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0040_alter_systemsetting_setting_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='mlm_count',
        ),
        migrations.RemoveField(
            model_name='program',
            name='urd_count',
        ),
        migrations.CreateModel(
            name='ProgramSectionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_counts', to='controller.program')),
            ],
            options={
                'unique_together': {('program', 'section')},
            },
        ),
    ]
